sudo: required
language: node_js
node_js:
  - "lts/*"
go:
  - master
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
before_script:
  - npm install -g gulp-cli
script: gulp
deploy:
  provider: pages
  local-dir: public
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: source
cache: npm
notifications:
  email:
    on_success: never
