dist: xenial
sudo: required
language: node_js
node_js:
  - "lts/*"
go:
  - master
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
  - npm i natives
before_script:
  - npm install -g gulp-cli
  - npm install -g postcss-cli
  - npm install -g autoprefixer
script: gulp
deploy:
  provider: pages
  local-dir: public
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: source
notifications:
  email:
    on_success: never
